### ISSUE TITLE
Request. Bookmark marks in navigation.

### ISSUE THREAD

**Issue by garrett85** [Bolls-Bible/bain#8]
I don't see anywhere to normal discussion, feedback, or request so my apologies if this is the wrong place to put this. But there's two small features I would like to see.

I like the fact the we have bookmarks and notes but unless your directly over the text where you a bookmark you wouldn't know it was there. I would like to see some kind of a flag on the left hand chapter navigation showing that you have a bookmark or note in that particular book/chapter.

I would also like to maybe see two special bookmarks, one primary bookmark for each testament, one for the old and one for the new.

My thoughts after using Bolls. Thanks.

**Comment by Bohooslav** [comment]
Idk, I'll try to investigate it. I may put some color dots under chapter numbers indicating that there are notes/bookmarks.

I hope there is no much sense to put also highlights there, since there may be too much of them

**Comment by Bohooslav** [comment]
Sorry for late reply, didn't get any notifications from Github. Now have a short vacation, will do what I can.

**Comment by Bohooslav** [comment]
You meant something like this in navigation? 
![image](https://user-images.githubusercontent.com/35796539/230793646-bf08792b-1efb-4115-9224-0590b617ac77.png)

**Comment by Bohooslav** [comment]
https://github.com/Bolls-Bible/bain/pull/10

**Comment by Bohooslav** [comment]
@garrett85 this feature is already released for a while and seems to be stable. Please give feedback and close this issue if I fulfilled your desire. Thanks

**Comment by rik-shaw** [comment]
I like the approach you used, and I understand that if you had dots under each chapter for hilights it would be too busy / not very informative since it may just be that every single chapter would have marks under it.

This said, having a separate view for highlights+notes may really be nice. Sometimes when I am rushed it is nice to read through the verses I have hilighted for a book when I don't have time to read more. Sorting it by when the highlight was made is also nice, you can then re-live what you were doing and where you were when the scripture made an impact on you. So the hilight list could be sorted by chronological or scripture order.

This may take some consideration if it is in line with the approach of Bolls, and if it is clear enough to implement well without being cluttered. But I personally think that users may appreciate it.

**Comment by Bohooslav** [comment]
I am not sure if I understand everything, but here is what I can do now.  You can view your bookmarks in your profile, which is located right there (your name should be there)

![image](https://github.com/Bolls-Bible/bain/assets/35796539/10d2b90b-f77b-44d3-9f8e-e97e4274151c)

Currently, they are sorted from latest to oldest, but I guess it makes sense to add filters, to be able to filter and order bookmarks by book / translation. I hope that should enough.
